# HTTP Server (Tomcat) Port
server:
  port: 8080

spring:
  application:
    name: gateway

zuul:
  prefix: /api
  routes:
    predictive-analytics-service:
      path: /**
      url: http://localhost:7070
      serviceId: loan-service
      
#zuul.routes.producer.path : /api/**
#zuul.routes.producer.serviceId : microservice    
      

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
    metadataMap:
      instanceId:  gateway:5
      #instanceId: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:6060/eureka/
    registerWithEureka: false


# Useful for debugging purposes
feign:
  hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000